name: C/C++ CI

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2
    - run: mkdir build
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.4.0
      with:
        version: 5.12.7
    - name: Configure
      working-directory: build
      shell: bash
      run: cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: Build
      working-directory: build
      shell: bash
      run: cmake --build . --config Release
    - name: Pack
      working-directory: build
      shell: bash
      run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            /c/Program\ Files/CMake/bin/cpack -G ZIP
          else
            cpack -G ZIP
          fi


